### PR TITLE
Buffer.from polyfill

### PR DESCRIPTION
**Pull request by gr2m**

### CODE REVIEW

**Comment by gr2m** [comment]
@StanleyGoldman let me know if that fixes your problem :)

**Comment by gr2m** [comment]
I’ve setup automated releases and removed `build.js`, once the release is out you’ll be able to install with `npm install octokit-rest-for-node-v0.12`

**Comment by gr2m** [comment]
@StanleyGoldman lol we triggered their spam detection
https://travis-ci.org/gr2m/octokit-rest-for-node-v0.12/builds/347561174#L2038

for the time being, you can install it with `npm install octokit-rest-nothing-to-see-here-kthxbye`

**Comment by StanleyGoldman** [comment]
wha??
How did you trigger their spam detection?

**Comment by StanleyGoldman** [comment]
Ohh... we triggered NPMs spam detection

**Comment by gr2m** [comment]
their spam detection is new :) I guess the problem was that I just created a new account and right away published a package. I've sent their support an email and hope they will clear up things soon

**Pull request merged**
